### ISSUE TITLE
Unique Username and Password with Database Functionality

### ISSUE THREAD

**Issue by Rayoil20** [Rayoil20/MindHack-soen341project2023#6]
Initiator: Student

Goal - To have a unique username and password for my student profile.

As an end user, I want to be able to create a unique username and password for my student profile, so that my account is secure and only accessible by me.

Story Points: 7
Risks: 5

Acceptance Criteria:

The website ought to provide a method for determining whether a user's entered username is original and not currently in use by another user.
The database should securely encrypt and store the user's inputted password.
To offer a seamless user experience, the database should be able to access user information rapidly and effectively.

**Comment by sophiehajjar** [comment]
This issue will be covered during sprint 3
